// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mts.Infrastructure;

#nullable disable

namespace MTS.RazorStarter.Migrations
{
    [DbContext(typeof(MtsDbContext))]
    partial class MtsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Mts.Domain.ComponentPart", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("MakeBuy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("make_buy");

                    b.Property<string>("VendorPartNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor_part_no");

                    b.HasKey("ItemId");

                    b.ToTable("component_part", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.CutSheet", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("Gauge")
                        .HasColumnType("TEXT")
                        .HasColumnName("gauge");

                    b.Property<string>("MachineType")
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_type");

                    b.Property<string>("MaterialSpec")
                        .HasColumnType("TEXT")
                        .HasColumnName("material_spec");

                    b.Property<string>("SheetSize")
                        .HasColumnType("TEXT")
                        .HasColumnName("sheet_size");

                    b.HasKey("ItemId");

                    b.ToTable("cut_sheet", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.CutSheetBomLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("component_item_id");

                    b.Property<int>("CutSheetRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cut_sheet_revision_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("LineNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_no");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PartNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("part_no");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.HasKey("Id");

                    b.HasIndex("ComponentItemId");

                    b.HasIndex("CutSheetRevisionId");

                    b.ToTable("cut_sheet_bom_line", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_no");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_type");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNo")
                        .IsUnique();

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.DocumentRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChecksumSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_current");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<string>("ReleaseState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("release_state");

                    b.Property<string>("RevisionCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("revision_code");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "RevisionCode")
                        .IsUnique();

                    b.ToTable("document_revision", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.FrameAssembly", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("AssemblyClass")
                        .HasColumnType("TEXT")
                        .HasColumnName("assembly_class");

                    b.Property<string>("FamilyCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_code");

                    b.HasKey("ItemId");

                    b.ToTable("frame_assembly", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.FramePart", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("DefaultFinish")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_finish");

                    b.Property<string>("FamilyCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("family_code");

                    b.Property<string>("MaterialSpec")
                        .HasColumnType("TEXT")
                        .HasColumnName("material_spec");

                    b.HasKey("ItemId");

                    b.ToTable("frame_part", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.FramePartCutSheetLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutSheetRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cut_sheet_revision_id");

                    b.Property<int>("FramePartRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frame_part_revision_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("link_type");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<decimal?>("UsageQty")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("usage_qty");

                    b.HasKey("Id");

                    b.HasIndex("CutSheetRevisionId");

                    b.HasIndex("FramePartRevisionId", "CutSheetRevisionId", "LinkType")
                        .IsUnique();

                    b.ToTable("frame_part_cut_sheet_link", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_no");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ItemNo")
                        .IsUnique();

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.ItemBom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BomRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bom_role");

                    b.Property<int>("ChildRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("child_revision_id");

                    b.Property<string>("FindNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("find_no");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("ParentRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_revision_id");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("qty");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ChildRevisionId");

                    b.HasIndex("ParentRevisionId");

                    b.ToTable("item_bom", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.ItemRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_current");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("ReleaseState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("release_state");

                    b.Property<string>("RevisionCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("revision_code");

                    b.Property<string>("RevisionNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("revision_note");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "RevisionCode")
                        .IsUnique();

                    b.ToTable("item_revision", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.RevisionDocumentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_revision_id");

                    b.Property<string>("DocumentRole")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document_role");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<int>("ItemRevisionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_revision_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRevisionId");

                    b.HasIndex("ItemRevisionId", "DocumentRevisionId", "DocumentRole")
                        .IsUnique();

                    b.ToTable("revision_document_link", (string)null);
                });

            modelBuilder.Entity("Mts.Domain.ComponentPart", b =>
                {
                    b.HasOne("Mts.Domain.Item", "Item")
                        .WithOne("ComponentPart")
                        .HasForeignKey("Mts.Domain.ComponentPart", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Mts.Domain.CutSheet", b =>
                {
                    b.HasOne("Mts.Domain.Item", "Item")
                        .WithOne("CutSheet")
                        .HasForeignKey("Mts.Domain.CutSheet", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Mts.Domain.CutSheetBomLine", b =>
                {
                    b.HasOne("Mts.Domain.Item", "ComponentItem")
                        .WithMany("ReferencedByCutSheetBomLines")
                        .HasForeignKey("ComponentItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mts.Domain.ItemRevision", "CutSheetRevision")
                        .WithMany("CutSheetBomLines")
                        .HasForeignKey("CutSheetRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentItem");

                    b.Navigation("CutSheetRevision");
                });

            modelBuilder.Entity("Mts.Domain.DocumentRevision", b =>
                {
                    b.HasOne("Mts.Domain.Document", "Document")
                        .WithMany("Revisions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Mts.Domain.FrameAssembly", b =>
                {
                    b.HasOne("Mts.Domain.Item", "Item")
                        .WithOne("FrameAssembly")
                        .HasForeignKey("Mts.Domain.FrameAssembly", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Mts.Domain.FramePart", b =>
                {
                    b.HasOne("Mts.Domain.Item", "Item")
                        .WithOne("FramePart")
                        .HasForeignKey("Mts.Domain.FramePart", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Mts.Domain.FramePartCutSheetLink", b =>
                {
                    b.HasOne("Mts.Domain.ItemRevision", "CutSheetRevision")
                        .WithMany("FramePartCutSheetLinksAsCutSheet")
                        .HasForeignKey("CutSheetRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mts.Domain.ItemRevision", "FramePartRevision")
                        .WithMany("FramePartCutSheetLinksAsFramePart")
                        .HasForeignKey("FramePartRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CutSheetRevision");

                    b.Navigation("FramePartRevision");
                });

            modelBuilder.Entity("Mts.Domain.ItemBom", b =>
                {
                    b.HasOne("Mts.Domain.ItemRevision", "ChildRevision")
                        .WithMany("BomParents")
                        .HasForeignKey("ChildRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mts.Domain.ItemRevision", "ParentRevision")
                        .WithMany("BomChildren")
                        .HasForeignKey("ParentRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildRevision");

                    b.Navigation("ParentRevision");
                });

            modelBuilder.Entity("Mts.Domain.ItemRevision", b =>
                {
                    b.HasOne("Mts.Domain.Item", "Item")
                        .WithMany("Revisions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Mts.Domain.RevisionDocumentLink", b =>
                {
                    b.HasOne("Mts.Domain.DocumentRevision", "DocumentRevision")
                        .WithMany("RevisionLinks")
                        .HasForeignKey("DocumentRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mts.Domain.ItemRevision", "ItemRevision")
                        .WithMany("DocumentLinks")
                        .HasForeignKey("ItemRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentRevision");

                    b.Navigation("ItemRevision");
                });

            modelBuilder.Entity("Mts.Domain.Document", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Mts.Domain.DocumentRevision", b =>
                {
                    b.Navigation("RevisionLinks");
                });

            modelBuilder.Entity("Mts.Domain.Item", b =>
                {
                    b.Navigation("ComponentPart");

                    b.Navigation("CutSheet");

                    b.Navigation("FrameAssembly");

                    b.Navigation("FramePart");

                    b.Navigation("ReferencedByCutSheetBomLines");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Mts.Domain.ItemRevision", b =>
                {
                    b.Navigation("BomChildren");

                    b.Navigation("BomParents");

                    b.Navigation("CutSheetBomLines");

                    b.Navigation("DocumentLinks");

                    b.Navigation("FramePartCutSheetLinksAsCutSheet");

                    b.Navigation("FramePartCutSheetLinksAsFramePart");
                });
#pragma warning restore 612, 618
        }
    }
}
